// SS220 EDIT: shared compile-time constants for modular xeno_races.

#define XENO_HIVE_PATHOGEN "xeno_hive_pathogen"

#define XENO_CASTE_BODYBURSTER "Bodyburster"
#define XENO_CASTE_LANKY "Lanky"

#define PATHOGEN_CREATURE_BURSTER "Bloodburster"
#define PATHOGEN_CREATURE_SPRINTER "Sprinter"
#define PATHOGEN_CREATURE_POPPER "Popper"
#define PATHOGEN_CREATURE_NEOMORPH "Neomorph"
#define PATHOGEN_CREATURE_BLIGHT "Blight"
#define PATHOGEN_CREATURE_BRUTE "Brute"
#define PATHOGEN_CREATURE_VENATOR "Venator"
#define ALL_PATHOGEN_CREATURES list(PATHOGEN_CREATURE_BURSTER, PATHOGEN_CREATURE_SPRINTER, PATHOGEN_CREATURE_POPPER, PATHOGEN_CREATURE_NEOMORPH, PATHOGEN_CREATURE_BLIGHT, PATHOGEN_CREATURE_BRUTE, PATHOGEN_CREATURE_VENATOR)

#define PATHOGEN_STRUCTURE_CORE "blight core"
#define PATHOGEN_STRUCTURE_COCOON "mycelial cocoon"

#define POPPER_COCOON_DEAD -1
#define POPPER_COCOON_GROWING 0
#define POPPER_COCOON_GROWN 1
#define POPPER_COCOON_HATCHED 2

#define FLAG_EMBRYO_HYBRID 2
#define FLAG_EMBRYO_PATHOGEN 4

#define LANGUAGE_PATHOGEN "Pathogen"
#define LANGUAGE_PATHOGEN_MIND "Pathogen Mind"

#define TRAIT_PATHOGEN_OVERMIND "t_pathogen_overmind"
#define OVERMIND_TRAIT "pathogen_overmind"

#define BODY_BURSTING (1<<8)
#define BLOOD_BURSTING BODY_BURSTING

#define XENO_SPEED_LANKY 0.1
#define XENO_SPEED_RAPTOR -0.9
#define XENO_ARMOR_TIER_9 60

#define XENO_PLASMA_TIER_7 700 * XENO_UNIVERSAL_PLASMAMULT
#define XENO_PLASMA_TIER_9 900 * XENO_UNIVERSAL_PLASMAMULT

#define LARVA_STATE_BLOODY 0
#define LARVA_STATE_NORMAL 1
#define LARVA_STATE_MATURE 2

#define SPORES_WAITING 0
#define SPORES_DEPLOYING 1
#define SPORES_DEPLOYED 2

#define is_pathogen_creature(A) (istype(A, /mob/living/carbon/xenomorph) && istype(A?:caste, /datum/caste_datum/pathogen))

#undef ALL_XENO_HIVES
#define ALL_XENO_HIVES list(XENO_HIVE_NORMAL, XENO_HIVE_CORRUPTED, XENO_HIVE_ALPHA, XENO_HIVE_BRAVO, XENO_HIVE_CHARLIE, XENO_HIVE_DELTA, XENO_HIVE_FERAL, XENO_HIVE_TAMED, XENO_HIVE_MUTATED, XENO_HIVE_FORSAKEN, XENO_HIVE_YAUTJA, XENO_HIVE_RENEGADE, XENO_HIVE_TUTORIAL, XENO_HIVE_PATHOGEN)

#undef ALL_XENO_CASTES
#define ALL_XENO_CASTES list(XENO_CASTE_LARVA, XENO_CASTE_PREDALIEN_LARVA, XENO_CASTE_FACEHUGGER, XENO_CASTE_LESSER_DRONE, XENO_CASTE_DRONE, XENO_CASTE_RUNNER, XENO_CASTE_SENTINEL, XENO_CASTE_DEFENDER, XENO_CASTE_BURROWER, XENO_CASTE_CARRIER, XENO_CASTE_HIVELORD, XENO_CASTE_LURKER, XENO_CASTE_WARRIOR, XENO_CASTE_SPITTER, XENO_CASTE_BOILER, XENO_CASTE_PRAETORIAN, XENO_CASTE_CRUSHER, XENO_CASTE_RAVAGER, XENO_CASTE_QUEEN, XENO_CASTE_PREDALIEN, XENO_CASTE_HELLHOUND, XENO_CASTE_SOLDIER, XENO_CASTE_KING, XENO_CASTE_BODYBURSTER, XENO_CASTE_LANKY, PATHOGEN_CREATURE_BURSTER, PATHOGEN_CREATURE_SPRINTER, PATHOGEN_CREATURE_POPPER, PATHOGEN_CREATURE_NEOMORPH, PATHOGEN_CREATURE_BLIGHT, PATHOGEN_CREATURE_BRUTE, PATHOGEN_CREATURE_VENATOR)
